nextcloud/circles

- lib/Db/CircleProviderRequestBuilder.php
As far as I could tell it was also never used.
> For some reason the querybuilder messes up with aliases on update on sqlite

- lib/ShareByCircleProvider.php
This lead to the error that if there was an incomming circle share any
other share would have been shared by that user.
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>
> When a node is provided we should use it

- js/circles.app.results.members.js
This was initially a heads-up from javier.llamas on the translation platform about line 64.
"Successfully" also removed. If there is a non-successful way of doing things, or if it failed beforehand, i can reinstate it.
Being expelled/excluded from a circle rather than removed makes more sense for me, but i opted out of it since it is just more advanced for not a whole lot of reward, and potential problems in translation.
> Spelling: The member, non plural, of circle.

- templates/settings.admin.php
This string doesn't appear to be translatable btw.
It can be seen at the bottom of /settings/admin/additional in 12.3
> Spelling: Plural Nextcloud linking

- lib/ShareByCircleProvider.php
When a share was shared with a circle the formatted _shared with_ field included the name, type and owner of the circle to provide a user friendly information about the circle to the Sharing UI. However, the ID of the circle was missing; this pull request adds it to make possible to identify the circle that a share was shared with.
This is needed, for example, to properly filter known shares with a circle in the _Sharing_ tab of the details view of the Files app. When a file is already shared with a sharee the sharee is filtered from the suggestions; this is done [by comparing the `share_with` field from the suggested sharee with the `share_with` field of all the shares of the file](https://github.com/nextcloud/server/blob/5f06380a4f4c8e49d8367825be119feba360b380/core/js/sharedialogview.js …
> Include circle short ID in formatted "shared with" field

- lib/Api/v1/Circles.php
- lib/Db/CirclesRequest.php
- lib/Db/CirclesRequestBuilder.php
- lib/Service/CirclesService.php
> adding a 2nd parameter to joinedCircles()

- lib/Controller/MembersController.php
If user enumeration is disabled in nextcloud core, then circle can
be used to circumvent this measure. For example the adduser button
in the user facing circle UI allows enumeration of all registered
users.
This patch honors the choice made in
'shareapi_allow_share_dialog_user_enumeration'
for deciding if auto completion should present partial results.
This is in line with other apps, such as webdav, which reuse this
configuration choice to disable user enumeration.
In case this preference is set, all partial results are removed
from the results.
Fixes #152
> honor user enumeration prevention of the share api

- lib/Service/CirclesService.php
- lib/Service/EventsService.php
Including `name` and `description` attributes
> Better 'onSettingsChange' event handling to get old setting values

- lib/Service/CirclesService.php
- lib/Service/GroupsService.php
> Fix adding group with member limit `-1` or `0`

- lib/Controller/SharesController.php
`SharesController` extends `Controller` - not `BaseController`
and thus does not inherit `this->fail`.
Not sure if it should extend `BaseController` instead.
This is the fix with the least changes
that make error reporting in the logs work for me again.
> fix: add fail function to SharesController

- lib/Search/LocalUsers.php
Backport of https://github.com/nextcloud/circles/pull/462 and fix an issue where the displayname of search results doesn't get passed properly to the SearchResult instance
> [stable18] Fix collaborator search and include email matches

- js/circles.v1.circles.js
- js/circles.v1.js
- js/circles.v1.links.js
- js/circles.v1.members.js
- js/files/circles.files.app.js
The api files relied on an api global to handle responses:
```javascript
$.ajax({ ...
}).done(function (res) {
api.onCallback(callback, res);
}).fail(function () {
api.onCallback(callback, result);
});
```
In the files app this only worked
because circles.files.app.js added api as a global.
Remove that global and replace it with
```javascript
OCA.Circles.api
```
wherever it was used.
Signed-off-by: Azul <azul@riseup.net>
> fix: do not rely on `api` global

- lib/Command/MembersCreate.php
- lib/Search/GlobalScaleUsers.php
- lib/Service/GSUpstreamService.php
- lib/Service/GlobalScaleService.php
> Make all instances of `Request()` aware of the `self_signed_cert` setting

- lib/Service/CirclesService.php
This allows to get a circle details with the member list even if no current user is available (in a background job) in case the API consumer needs a full list of members, e.g. to issue notifications to them.
Should fix #563
> Allow to get circle details with forceAll

- lib/Service/CirclesService.php
> enforce forceAll

- lib/AppInfo/Capabilities.php
- lib/Command/MembersList.php
- lib/Db/CoreQueryBuilder.php
- lib/Db/MemberRequest.php
- lib/FederatedItems/CircleCreate.php
- lib/FederatedItems/MassiveMemberAdd.php
- lib/FederatedItems/SingleMemberAdd.php
- lib/Migration/Version0022Date20220526113601.php
- lib/Migration/Version0022Date20220601121545.php
- lib/Model/Circle.php
- lib/Model/Member.php
- lib/Model/ModelManager.php
- lib/Service/CircleService.php
- lib/Service/ConfigService.php
- lib/Service/FederatedUserService.php
- lib/Service/MemberService.php
- lib/Service/SyncService.php
- lib/StatusCode.php
> +invitedBy

- lib/AppInfo/Capabilities.php
- lib/Circles/FileSharingBroadcaster.php
- lib/FederatedItems/SingleMemberAdd.php
- lib/GlobalScale/FileShare.php
- lib/GlobalScale/MemberAdd.php
- lib/Model/Circle.php
Spelling unification in Transifex.
> l10n: Spelling unification

- appinfo/routes.php
Related: https://github.com/nextcloud/contacts/pull/2283
Signed-off-by: Jonas Meurer <jonas@freesources.org>
> Change API route for renaming circles from `displayName` to `name`

- lib/Service/CircleService.php
Instead of stripping all non-ascii characters (which doesn't work well
with non-latin scripts), do minimal sanitization for `sanitizedName`
that can be used as filename and in URLs:
* Replace `/` with `-` to prevent directory traversal
* Remove characters that create problems on certain filesystems
* Remove leading spaces or dots to prevent hidden files
> Minimal invasive sanitization for `sanitizedName`

- lib/Db/CircleRequest.php
Until now, only `displayName` was changed.
> Set properties `name` and `sanitizedName` when changing a circles name

- lib/AppInfo/Application.php
- lib/Events/CircleEditedEvent.php
- lib/Events/CircleGenericEvent.php
- lib/Events/CircleMemberEditedEvent.php
- lib/Events/CircleMemberGenericEvent.php
- lib/Events/CircleMemberRequestedEvent.php
- lib/Events/CircleResultGenericEvent.php
- lib/Events/EditingCircleEvent.php
- lib/Events/EditingCircleMemberEvent.php
- lib/Events/MembershipsEditedEvent.php
- lib/Events/RequestingCircleMemberEvent.php
- lib/FederatedItems/CircleEdit.php
- lib/FederatedItems/CircleJoin.php
- lib/FederatedItems/MassiveMemberAdd.php
- lib/FederatedItems/MemberDisplayName.php
- lib/FederatedItems/MemberLevel.php
- lib/FederatedItems/SingleMemberAdd.php
- lib/Listeners/Examples/ExampleAddingCircleMember.php
- lib/Listeners/Examples/ExampleRequestingCircleMember.php
- lib/Listeners/Files/AddingMember.php
- lib/Listeners/Files/MemberAdded.php
- lib/Listeners/Notifications/RequestingMember.php
- lib/Model/Federated/FederatedEvent.php
- lib/Service/CircleService.php
- lib/Service/EventService.php
- lib/Service/RemoteDownstreamService.php
- more events regarding edit on members
- the idea is to remove the 'massive members add' event as it will be unmanageable in some use-case. 
- WIP: need to check what would happens on duplicate single on a remote instance if we keep the faulty members in the event
> rework on some new members' events

- lib/Db/CircleRequest.php
- lib/Db/CoreQueryBuilder.php
- lib/Model/Circle.php
- lib/Model/ModelManager.php
The idea is to keep the basic request (getCircles & getMembers) working even if the table 'membership' is emptied, using direct link between initiator and the table 'member', instead of only using the table 'membership' to manage complete inheritance
> Bypass initiator from 'membership' using direct 'member'

- lib/Service/GlobalScaleService.php
to bypass the non-yet-fixed issue that some GS setup require to use internal address
> priority on gss.mockup

- lib/Api/v1/Circles.php
getMember used to throw an exception in case the circle didn't exist or user was not a member, so in order to avoid misbehaviour we should at least throw something instead of just a noop and return.
> Throw instead of doing nothing

- lib/Model/Member.php
Because the name of a secret circle might be discovered, a new member cannot directly join it (working like a closed circle)
> members cannot directly join a Secret Circle

- lib/Service/ConfigService.php
`$knownPath` may by `null` in `ConfigService->linkToRoute()`. `rtrim()`
requires a string as first argument.
Fixes: #774
Signed-off-by: Jonas Meurer <jonas@freesources.org>
> Check if `$knownPath` is set before invoking `rtrim()`

- lib/Collaboration/v2/CollaboratorSearchPlugin.php
> verify shareType in params

- lib/Service/CircleService.php
The current definition returns 'Nextcloud User owned by userId'.
This will only returns 'Nextcloud User'
> fix definition on single circles

- lib/Db/CircleRequest.php
- lib/Db/CoreQueryBuilder.php
- lib/Model/Probes/MemberProbe.php
- lib/Service/MemberService.php
- lib/Service/MembershipService.php
If we keep caching memberships of owner of NO_OWNER Circles, the owner will be returned on `getInheritedMembers()`.
This PR will fix this while keeping the sql request from failing when searching for existing Circles based on a FederatedUser used as Owner of a NO_OWNER Circle
> owner of NO_OWNER should not have memberships cached

- lib/Model/FederatedUser.php
getLink always through so far? Even if you where a member and have a link.
Also the getLink never returned a link?
> Make getLink work

- lib/Service/MigrationService.php
Since 5a7ff3c713f246d8b5f5da72ee0540223ef6d79e Secret Circles on version prior to 22.x were requesting join request to be confirmed by a moderator.
Let's pass this settings during migration
> force join_request on old secret circles

- lib/Controller/EventWrapperController.php
reduce this sleep delay from 5s to 4s to fix an issue with the `occ circles:check` command which uses a default 5s libcurl timeout.
See e.g. https://github.com/nextcloud/circles/issues/731#issuecomment-889963271
> Reduce the sleep time in test-dummy-token handler

- lib/Db/CircleRequest.php
- lib/Db/CircleRequestBuilder.php
- lib/Db/CoreQueryBuilder.php
- lib/Service/FederatedUserService.php
Lighten slightly a frequently used request:
- removing useless _DISTINCTROW_
- _INNER_ instead of _LEFT_
- removing useless _ORDER_
Old version:
> SELECT DISTINCTROW `single` . `unique_id` , `single` . `name` , `single` . `display_name` , `single` . `sanitized_name` , `single` . `source` , `single` . `description` , `single` . `settings` , `single` . `config` , `single` . `contact_addressbook` , `single` . `contact_groupname` , `single` . `creation` FROM `oc_circles_circle` `single` LEFT JOIN `oc_circles_member` `single_member` ON `single_member` . `circle_id` = `single` . `unique_id` WHERE ( ( `single_member` . `user_id` = ? ) AND ( `single_member` . `user_type` = ? ) AND ( `single_member` . `instance` = ? ) AND ( `single_member` . `level` >= ? ) ) AND ( ( `single` . `config` & ? ) > ? ) …
> lighten select for single circle

- lib/AppInfo/Application.php
- lib/Db/CoreQueryBuilder.php
- lib/Db/MountRequest.php
- lib/Events/Files/PreparingFileShareEvent.php
- lib/Events/PreparingCircleMemberEvent.php
- lib/FederatedItems/Files/FileShare.php
- lib/FederatedItems/MassiveMemberAdd.php
- lib/FederatedItems/SingleMemberAdd.php
- lib/Listeners/Files/CreatingShareSendMail.php
- lib/Listeners/Files/MemberAddedSendMail.php
- lib/Listeners/Files/PreparingMemberSendMail.php
- lib/Listeners/Files/PreparingShareSendMail.php
- lib/Listeners/Files/ShareCreatedSendMail.php
- lib/Migration/Version0023Date20211216113101.php
- lib/Model/Federated/FederatedEvent.php
- lib/Model/ModelManager.php
- lib/Model/ShareToken.php
- lib/Model/ShareWrapper.php
- lib/Service/ConfigService.php
- lib/Service/EventService.php
- lib/Service/FederatedEventService.php
- lib/Service/RemoteUpstreamService.php
- lib/Service/SendMailService.php
- lib/Service/ShareTokenService.php
- lib/ShareByCircleProvider.php
So, the hard part was to keep the clear password on the master instance while creating shares on slaves (in global scale setup)
- When a new member is added, or a new share is created, the main instance will generate a list of Clean Passwords and their Hash. Hash will be shared to slaves to be used when generating the share token,
- Each slave will use a different hashed password for each members and inherited members of the circle. And will returns the list of generate share,
- Main instance get informations about the generate shares, and generate a mail per members and inherited members with the right password from the list.
> enforce password on new share

- lib/Service/SyncService.php
The method returns an exception if a user is already in the circle; making the sync failing
> ignore exception to group sync

- lib/FederatedItems/MemberLevel.php
- lib/Model/Membership.php
- lib/Service/MaintenanceService.php
- lib/Service/MembershipService.php
fix 2 issues:
- update old owner membership on ownership transfer,
- update membership if inherited level is kept but inheritance path changed
> Fix loosing memberships in low depth

- lib/IFederatedUser.php
No idea why it was missing ...
The method is already available in both class that `implements IFederatedUser`: `FederaedUser` and `Member`.
> +getSingleId(): string;

- lib/FederatedItems/SingleMemberAdd.php
There is an issue currently where if Circle is set as INVITE when adding an external member.
This fix will accept memberships for external member without any need of confirmation from the said external member.
INVITE means "new member needs to confirm their membership (invitation)
> set member as INVITED only if not external

- appinfo/info.xml
- appinfo/routes.php
- lib/Circles/FileSharingBroadcaster.php
- lib/Command/CirclesSetting.php
- lib/Controller/AdminController.php
- lib/Controller/LocalController.php
- lib/Db/CircleRequest.php
- lib/FederatedItems/CircleSetting.php
- lib/GlobalScale/FileShare.php
- lib/GlobalScale/MemberAdd.php
- lib/Listeners/Files/PreparingMemberSendMail.php
- lib/Listeners/Files/PreparingShareSendMail.php
- lib/Model/Circle.php
- lib/Service/CircleService.php
- lib/Service/ConfigService.php
- lib/Service/SendMailService.php
* Enforcing password protection if the Enforce password protection is enabled.
* Enforcing password protection if the Circle App is configured to: 
`./occ config:app:set --value '1' circles enforce_password`
* Enforcing password protection if the Circle's settings is configured to:
`./occ circles:manage:setting y8JczmViR3zZraCXhbpfR8v4x8s5A8c enforce_password true`
```
$ ./occ circles:manage:setting y8JczmViR3zZraCXhbpfR8v4x8s5A8c 
{
"enforce_password": "true",
"password_single_enabled": "true",
"password_single": "3|$argon2id$v=19$m=65536,t=4,p=1$NktudFp4UmluSGZtRGhEeA$VJuD1vhKuKG+oFFT1nlmXHU3O3aTUw1ZFkjW8Vw9gxU"
}
```
```
$ ./occ circles:manage:setting y8JczmViR3zZraCXhbpfR8v4x8s5A8c enforce_password true
$ ./occ circles:manage:setting y8JczmViR3zZraCXhbpfR8v4x8s5A8c …
```
> allow configuration of one single password per circle

- lib/Command/CirclesCheck.php
Might be interesting to verify if the loopback request takes more than usual:
```
$ ./occ circles:check
[...]
- Creating async FederatedEvent 62337a0d-38a8-4864-b66a-18e44fb00db3 (took 135ms)
[...]
```
> display spent time on request

- lib/CirclesManager.php
- lib/Command/CirclesConfig.php
- lib/Exceptions/RemoteCircleException.php
- lib/Exceptions/SuperSessionException.php
- lib/FederatedItems/CircleConfig.php
- lib/FederatedItems/CircleDestroy.php
- lib/Model/Circle.php
- lib/Model/Member.php
- lib/Model/Probes/CircleProbe.php
- lib/Service/CircleService.php
- lib/Service/ConfigService.php
- lib/Service/FederatedUserService.php
- lib/StatusCode.php
- Allow an App to gain control over a Circle:
```
/** @var CirclesManager $circleManager */
$circleManager = \OC::$server->get(CirclesManager::class);
$circleManager->startSuperSession();
$circleManager->flagAsAppManaged('tnxgB4xdBpgew6H4l9CJXEUauUNql71');
$circleManager->stopSession();
```
- When marked as AppManaged, the Circle cannot be removed from the OCS API (ie. Contacts App)
- Allow an App to create its own Entity:
```
/** @var CirclesManager $circleManager */
$circleManager = \OC::$server->get(CirclesManager::class);
$circleManager->startAppSession('my app', 11010);
$circle = $circleManager->createCircle(
'Test Circle',
$circleManager->getLocalFederatedUser('test1')
);
```
_identifying as an App does not give more rights. To have rights over a Circle, the Entity of the App needs …
> limit some feature when Circles is managed by an app

- .github/workflows/phpunit.yml
Just to make it easier to parse and replace master to stable* when stable-branching
> use master to test oci

- lib/Db/ShareWrapperRequest.php
- lib/FederatedItems/Files/FileShare.php
- lib/Listeners/Files/DestroyingCircle.php
- lib/Listeners/Files/MembershipsRemoved.php
- lib/Model/FileCacheWrapper.php
- lib/Model/Probes/CircleProbe.php
- lib/Service/MaintenanceService.php
- lib/Service/MembershipService.php
- lib/Service/ShareWrapperService.php
- lib/Tools/Traits/TDeserialize.php
The idea is to cache the result from getSharedWith() which can be requested multiple times (at least 4) when loading a new page on Files App. 
Each cache is identified by a key based on:
- the singleId of the initiator, 
- the nodeId of the request, can be `0`
- the checksum of the `Probe` object.
The cache related to the singleId of the membership is reset when membership is updated.
All the cache is clear when creating/editing/deleting a share. _(It might be interesting to filter the memberships affected by the share)_
> Cache getSharedWith() result

- lib/Model/Circle.php
- lib/Service/FederatedUserService.php
> [stable22] small edit

- lib/Model/FederatedUser.php
to avoid unhandled exception in case of badly configured circles app when running occ user:list
> check owner attendance

- lib/Db/ShareWrapperRequest.php
- lib/Listeners/Files/DestroyingCircle.php
- lib/Listeners/Files/MembershipsRemoved.php
- lib/Service/MaintenanceService.php
- lib/Service/ShareWrapperService.php
1000!
Issue:
- userA shares a first file to a Circle (including userA and userB),
- userB leaves the share,
- Circle is destroyed, a new Circle is created (including userA and userB)
- Sharing the same file.
Fix:
- split getUserShares from a single user to a circle and getAllShares to a circle
- when a circle is deleted, or when a member is removed, get affected shares ids
- get orphans on a maintenance process
- delete all shares and child based on ids.
The request that get all orphan shares, based on `parent` `not null` and entry with `id`=`parent` exists:
```
SELECT `sh`.`id`, `sh`.`share_type`, `sh`.`share_with`, `sh`.`uid_owner`, `sh`.`uid_initiator`, `sh`.`parent`, `sh`.`item_type`, `sh`.`item_source`, `sh`.`item_target`, `sh`.`file_source`, `sh`.`file_target`, `sh`.`permissions`, …
```
> remove child shares

- lib/FederatedItems/CircleEdit.php
- lib/Listeners/DeprecatedListener.php
- lib/Service/MaintenanceService.php
> [stable23] update displayName

- lib/Model/ShareWrapper.php
`import()` is used to deserialize the model, array keys should fit the one used in `jsonSerialize()`
> fix array key on import()

- lib/Db/ShareWrapperRequest.php
Reduces the number of database table joins in a single call to share providers getShareWith function from 10 to 6.
This is the current database query, which is executed on each call to circles share provider and its average slow query log time:
```
Query_time: 0.018108  Lock_time: 0.001674  Rows_sent: 5  Rows_examined: 919
```
<details>
<summary>Current share provider db query</summary>
```
SELECT `sh`.`id`,
`sh`.`share_type`,
`sh`.`share_with`,
`sh`.`uid_owner`,
`sh`.`uid_initiator`,
`sh`.`parent`,
`sh`.`item_type`,
`sh`.`item_source`,
`sh`.`item_target`,
`sh`.`file_source`,
`sh`.`file_target`,
`sh`.`permissions`,
`sh`.`stime`,
`sh`.`accepted`,
`sh`.`expiration`,
`sh`.`token`,
`sh`.`mail_send`,
`sh_cc`.`unique_id` AS `sh_cc_unique_id`,
`sh_cc`.`name` AS `sh_cc_name`, …
```
> Improve performance of share provider

- lib/Command/CirclesConfig.php
fix as `'super-session'` is set in `addOption()` on L106
> switch to getOption()

- lib/Service/RemoteStreamService.php
- lib/Tools/Traits/TStringTools.php
Avoid the use of `confirmKey` to encrypt headers content and spoof instance's identity
> confirmKey must be uuid

- lib/Service/ShareWrapperService.php
- lib/Tools/Traits/TDeserialize.php
renaming `deserializeArray` -> `deserializeItem`
> using deserializeList instead

- lib/Service/MigrationService.php
There is a current minor issue making the migration process to run even if there is nothing to migrate (fresh instance). 
The full migration process will reset memberships and recreate them, which is useless on a fresh instance.
On old instance (pre-22 with Circles already installed), Because the old tables were not drop after the migration, a negative use-case could be trigger:
- using Circles pre-22,
- migrating to nc22,
- reset the Circles app, using it to create your group of users,
- next upgrade, migration will try to migrate old data pre-22.
This fix will check that new table are not used and that the old table exists.
The drop of old tables will be done in 25
> confirm migration feasibility

- lib/FederatedItems/MassiveMemberAdd.php
Reverts nextcloud/circles#1077
merged too early, in RC state.
> Revert "[stable23] log failed member generation"

- lib/FederatedItems/MassiveMemberAdd.php
Reverts nextcloud/circles#1078
merged too early, during RC stage
> Revert "[stable22] log failed member generation"

- lib/Service/MigrationService.php
Reverts nextcloud/circles#1081
> Revert "[stable22] confirm migration feasibility"

- lib/ShareByCircleProvider.php
Internal Server Error\nReturn value of OCA\\Circles\\ShareByCircleProvider::getAllShares()
must be iterable, none returned in file '/var/www/html/apps-extra/circles/lib/ShareByCircleProvider.php' line 674
Signed-off-by: Carl Schwan <carl@carlschwan.eu>
> Fix getAllShare crash

- lib/Model/ShareWrapper.php
and fix translation as it seems I forgot to push it to stable22 in a previous PR of mine
> [stable22] Avoid using non-existing \OCP\Server::get

- js/files/circles.files.list.js
- templates/files/list.php
Elements in the files app have been renamed to avoid duplicate ids.
For https://github.com/nextcloud/server/pull/33320
> Rename selectors for files app elements

- lib/Db/ShareWrapperRequest.php
- lib/Service/ShareWrapperService.php
- lib/ShareByCircleProvider.php
- lib/ShareByCircleProviderDeprecated.php
A new `$shallow` argument was introduced to `IShareProvider::getSharesInFolder` in NC25 by https://github.com/nextcloud/server/pull/31728.
This PR adds this new argument and the necessary changes to make it work based on this example https://github.com/nextcloud/server/pull/31728/files#diff-dee1351696d7eae959761edf66c8e5a9052e28be73319733d857a9ab2d9fc967=
Looks like in the context of `ShareWrapperRequest`, the `$shallow` argument can't be used as we only have the `nodeId` so we cannot use the same method as in other places:
```php
if ($shallow) {
$qb->andWhere($qb->expr()->eq('f.parent', $qb->createNamedParameter($node->getId())));
} else {
$qb->andWhere($qb->expr()->like('f.path', $qb->createNamedParameter($this->dbConnection->escapeLikeParameter($node->getInternalPath()) . '/%')));
} …
```
> Add `$shallow` arg to `ShareByCircleProvider::getSharesInFolder`

- lib/ShareByCircleProvider.php
fix an exception when running `./occ ldap:show-remnants`
> ignore remnants

- .github/workflows/static-analysis.yml
Signed-off-by: Joas Schilling <213943+nickvergessen@users.noreply.github.com>
> Make psalm run on pushes to protected branches

- .gitignore
- composer.lock
- lib/Db/DeprecatedCirclesRequestBuilder.php
- lib/Tools/Db/ExtendedQueryBuilder.php
- tests/psalm-baseline.xml
Also updates `christophwurst/nextcloud` to run tests against latest `server`
Fix #1132
> Fix IQueryFunction to string compliance

- lib/CirclesManager.php
- lib/Service/CircleService.php
this is a quick fix, before the implementation of DataProbe (#1088)
> cache getCircles when executed from an other app

- lib/CirclesManager.php
might not be the best solution
> refresh cache on demand

- lib/Listeners/Files/RemovingMember.php
- lib/Service/ShareWrapperService.php
fixing an issue where shares were not removed when removing a member.
if a member is now removed, we checked for each inherited members if a share was done to the circle and parents.
> remove shares on removing members

- lib/Command/CirclesSetting.php
- lib/Db/ShareTokenRequest.php
- lib/FederatedItems/CircleSetting.php
- lib/Model/ShareWrapper.php
- lib/Service/ConfigService.php
- lib/Service/ShareTokenService.php
- lib/ShareByCircleProvider.php
- remove password on previous share if enforce password protection is disabled (globally, not just on current circle)
- update password on previous shares on static password changes (if password protection is enabled)
- adding '--test-password' option in ./occ circles:manage:setting to confirm password protection of shares
- notice log on getShareByToken if password protected, including hashed password
> update share on password change

- lib/Command/CirclesCheck.php
- tests/psalm-baseline.xml
This was removed at the release of 25 because of a missing element, restored in https://github.com/nextcloud/server/pull/35177
> refresh config

- lib/Command/CirclesMaintenance.php
- lib/Service/MaintenanceService.php
maintenance level 5 should update display name of users if older than 8 days since last update. 
`--force-refresh` will bypass this 8 days check.
> refresh display name

- lib/FederatedItems/CircleConfig.php
Required for Collectives to allow unflagging a circle as app managed and delete the circle in the same request.
> Make changes to circle config synchroneous

- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-oci.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- appinfo/routes.php
- css/files/circles.filelist.css
- js/files/circles.files.list.js
- lib/Api/v1/Circles.php
- lib/AppInfo/Application.php
- lib/Controller/DeprecatedController.php
- tests/psalm-baseline.xml
> [stable25] shared to circles

- Makefile
- appinfo/info.xml
- group can contains '@'
- probeCircles on search
- ignore personal's ownership requirement
> release 27.0.1

- lib/Model/FileCacheWrapper.php
- lib/ShareByCircleProvider.php
This fix an issue when sharing the top folder of an external storage.
path is empty in that case, meaning we should not return `false` when checking availability if path is empty but storage is managed by `files_external`
> support sharing files_external root

- lib/Db/CoreRequestBuilder.php
- lib/Db/ShareWrapperRequest.php
- lib/Model/ShareWrapper.php
- lib/Service/CircleService.php
- lib/ShareByCircleProvider.php
- psalm.xml
- tests/psalm-baseline.xml
manage `allow download` on shares to Circles using the same mechanism that internal shares and shareByMail.
- local account as members of a Circle will not be able to download the shared content,
- remote account (mail address) as members will not be able to see the download button.
the attributes is stored/converted the same way than in core.
> download permissions on share for internal/external members

- lib/Model/FileCacheWrapper.php
- lib/ShareByCircleProvider.php
> [stable27] support files_external

- lib/Command/CirclesSync.php
- lib/Db/AccountsRequest.php
- lib/Search/LocalUsers.php
- lib/Service/FederatedUserService.php
- lib/Service/MaintenanceService.php
- lib/Service/SyncService.php
sync and display name update should use a lot less resources
* Fixes: #1249
* Fixes: nextcloud/collectives#890
> lighter name update

- lib/Command/CirclesSync.php
- lib/Db/AccountsRequest.php
- lib/Search/LocalUsers.php
- lib/Service/FederatedUserService.php
- lib/Service/MaintenanceService.php
- lib/Service/SyncService.php
> [stable26] lighter name update

- lib/Service/SearchService.php
switching to getCircles() so that non member can search for visible circles
> switch to getCircles()

- lib/AppInfo/Application.php
- lib/Dashboard/TeamDashboardWidget.php
Resolves #1506 
@marcoambrosini @jancborchardt I used the generated avatars as they are also used in contacts right now
Needs upstream adjustments in the dashboard API:
> feat: Implement teams dashboard widget

- lib/Dashboard/TeamDashboardWidget.php
Fix for the issue mentioned by @nickvergessen in https://github.com/nextcloud/circles/pull/1510
> fix: Disable dashboard widget if no frontend is available

- lib/Dashboard/TeamDashboardWidget.php
Fixing the path to the app icon fixes dashboard widgets. Otherwise getting the widgets throws an error and all widgets are broken.
Adding the `icon-teams` CSS class fixes displaying the teams icon in the teams dashboard widget.
> fix(dashboard): Add `icon-teams` CSS class and fix path to app icon

- composer.lock
- lib/AppInfo/Application.php
- lib/FileSharingTeamResourceProvider.php
Example screenshot from the team overview in contacts:
> feat: Implement team resource provider for shared files

- lib/Service/ShareWrapperService.php
should fix generation of empty AND (()) request
Closes nextcloud/server#46196
> ignore empty fileIds

- lib/AppInfo/Application.php
- lib/Listeners/Notifications/RequestingMember.php
- lib/Service/NotificationService.php
For https://github.com/nextcloud/circles/issues/810
I only tested the case (circle needs invitation, user is invited, user press accept, notification is gone). 
Needs a careful review.
> feat: dismiss notification when accepting an invitation

- lib/Listeners/Notifications/RequestingMember.php
Regression from #1641
Adding a user to a system group triggers a notification:
> You have been invited by Circles into the Circle "group1"
:broom:
> fix(notifications): Don't trigger invite notifications for system groups

- lib/Circles/FileSharingBroadcaster.php
- lib/Service/MiscService.php
- lib/ShareByCircleProvider.php
Mostly replace `ILogger` with `LoggerInterface` and some minor cleanup (constructor property promotion).
Some places used the deprecated `logException`, this is easy to migrate: Simply use the appropriate log level on the logger and place the exception under the `exception` key in the context.
> refactor: Migrate away from deprecated `ILogger` to PSR-3

- lib/Listeners/AccountUpdated.php
Fixes nextcloud/contacts#3646
Although since https://github.com/nextcloud/circles/pull/1648 the display name of users is updated in a circle when it is changed in the user settings, the new display name was not shown if the user was then added to a circle; when the display name is changed it needs to be updated both for the circles and the members, similarly to how it is done [when updating the display name in the `MaintenanceService`](https://github.com/nextcloud/circles/blob/f725ecaffbfae29a98ef0eea745d5bcf6e64b90c/lib/Service/MaintenanceService.php#L432-L433).
Originally this pull request had an additional commit to set the display name of the associated member based on the `IUser` API instead of the account data when a user was created; this was done on the basis that the user was …
> Fix display name of new users

- lib/Db/CoreQueryBuilder.php
Fixes https://github.com/nextcloud/circles/issues/1697
> fix(CoreQueryBuilder): Use shorter prefixes to stay below 30 characters for Oracle <12.2

- lib/Notification/Notifier.php
> fix(notifications): Circles -> Teams references

- lib/ShareByCircleProvider.php
> [stable29] ignore non-circles share while extracting permissions

- lib/ShareByCircleProvider.php
> [stable30] ignore non-circles share while extracting permissions

- lib/ShareByCircleProvider.php
> [stable28] ignore non-circles share while extracting permissions

- lib/Db/ShareWrapperRequest.php
- lib/Model/ShareWrapper.php
- Before this commit, attributes added to a share were ignored when the share type was team/circles (share type `7`).
- Share attributes are not expected to contain any key or property named `enabled`.
Partial resolution of: https://github.com/nextcloud/server/issues/46920
This is a partial resolution because setting the `download` attribute may not fully enforce the correct download permissions. A follow-up PR in the server may be needed to update the `hideDownload` property of the share based on the value of `download` in the share attributes.
> fix(ShareWrapperRequest): Save share attributes on creation

- lib/Model/ShareWrapper.php
fix https://github.com/nextcloud/circles/pull/1731/files#r1825161374
> fix toArray on null

- lib/CirclesManager.php
- lib/Db/CoreQueryBuilder.php
- lib/Model/Federated/FederatedEvent.php
- lib/Service/CircleService.php
- lib/Service/FederatedEventService.php
- lib/Service/MemberService.php
- tests/phpunit.xml
- tests/unit/CirclesManagerTest.php
- tests/unit/lib/Controller/AdminControllerTest.php
- tests/unit/lib/Controller/LocalControllerTest.php
Before, the member entry that matched the `singleId` of the user and `level = 9` was used as initiator, which in practice means the member entry for the internal user circle of the user most of the time.
Instead, we want to use the member entry that matches `singleId` of the user and `circleId` of the circle in question.
This fixes the wrong `level` being set for `initiator` when calling `circleProbe()` with `DataProbe::INITIATOR`.
Fixes: #1757
> fix(CoreQueryBuilder): Use correct member entry for circle as initiator

- lib/Service/FederatedUserService.php
The singleId for a user doesn't change once it got generated, so no need to refresh the cache every 15 minutes. Let's cache it for one week instead.
> fix(FederatedUserService): Increase cache TTL for singleId to one week

- lib/Activity/ProviderParser.php
Otherwise activity emails are send with `/index.php/...` URLs
> fix(activity): ensure absolute URL are used

- lib/Api/v1/Circles.php
bypass initiator check when ran from CLI. this would fix an issue when running `./occ files:transfer-ownership`
~~~
```
Could not restore share with id 1:Invalid initiator : #0 /home/maxence/sites/nc30/nextcloud/apps/circles/lib/Service/CircleService.php(489): OCA\Circles\Service\FederatedUserService->mustHaveCurrentUser()
#1 /home/maxence/sites/nc30/nextcloud/apps/circles/lib/Api/v1/Circles.php(177): OCA\Circles\Service\CircleService->getCircle()
#2 /home/maxence/sites/nc30/nextcloud/lib/private/Share20/Manager.php(158): OCA\Circles\Api\v1\Circles::detailsCircle()
#3 /home/maxence/sites/nc30/nextcloud/lib/private/Share20/Manager.php(792): OC\Share20\Manager->generalCreateChecks()
#4 /home/maxence/sites/nc30/nextcloud/apps/files/lib/Service/OwnershipTransferService.php(463): …
```
> bypass user condition on cli

- lib/Db/CoreQueryBuilder.php
- lib/Db/MountPointRequest.php
- lib/Db/MountPointRequestBuilder.php
- lib/Db/MountRequest.php
- lib/Exceptions/MountPointNotFoundException.php
- lib/Migration/Version0031Date20241105133904.php
- lib/Model/ModelManager.php
- lib/Model/Mount.php
- lib/Model/Mountpoint.php
- lib/MountManager/CircleMountManager.php
- lib/MountManager/CircleMountProvider.php
- psalm.xml
- tests/psalm-baseline.xml
fix issues when sharing file on federated circles:
- should fully avoid duplicate name on remotely shared items
- compat with `Files_Sharing/External/Manager`
> fix duplicate name on fedcircle

- lib/Service/MembershipService.php
- lib/Service/ShareWrapperService.php
Reverts nextcloud/circles#1745
Due to being suspected to cause performance issue.
> Revert "remove caching for shares"

- lib/AppInfo/Capabilities.php
- tests/stub.phpstub
- Part of https://github.com/nextcloud/server/issues/48039
> feat: Add team resource providers capability

- lib/Command/SharesFiles.php
See https://github.com/nextcloud/circles/issues/1714#issuecomment-2602064835
> fix(occ): handle share wrappers that do not have a circle

- lib/Service/SendMailService.php
This prevent confusing users with emails containing link that lead to an error page.
> fix: Do not send a mail if public share is disabled

- lib/AppInfo/Application.php
- lib/FederatedItems/CircleEdit.php
- lib/Listeners/GroupChanged.php
- lib/Service/CircleService.php
My attempt to fix https://github.com/nextcloud/circles/issues/1828
Does not fully solve the linked issue.
Remaining problem: Existing members are not updated. Only the group circle.
> fix: propagate group name changes

- lib/Db/CoreRequestBuilder.php
- lib/Db/ShareWrapperRequest.php
- lib/Model/ShareWrapper.php
- lib/ShareByCircleProvider.php
This will first properly save the note in the DB, and then properly retrieve it.
Without it, we cannot display the share note to the user.
Before | After
-- | --
> fix(sharing): Handle share notes

- lib/Api/v1/Circles.php
no need for `joinedCircles()` to use `getCircles()`.
- `probeCircles()` ignore circles user is not a member of,
- `getCircles()` is heavier.
> switch to probeCircles

- tests/bootstrap.php
Hopefully fixes the CI: https://github.com/nextcloud/circles/actions/runs/15387616333/job/43289578650?pr=2012
Broken from https://github.com/nextcloud/server/pull/52945
> test: Fix autoloading

- lib/Db/EventWrapperRequest.php
On miss-configured federated teams  It can happens that same entry is generated twice. Not an issue to ignore it but we keep a trace in logs.
> ignore eventual duplicate entries

- lib/Db/EventWrapperRequest.php
- lib/Service/FederatedEventService.php
- There is no reason for a duplicate instance, unless faulty configuration of federated teams.
- The generated logs should help fixing it
- catch duplicate exception only
> fix(federated-teams): ignore duplicate instance and generate logs

- lib/Dashboard/TeamDashboardWidget.php
Fix is done as suggested by customer
> fix: translate name of dashboard widget

- lib/ShareByCircleProvider.php
https://github.com/nextcloud/circles/pull/1708 wasn't merged into master branch, so not available above 30.
Closes at least #2077 (maybe others)
> ignore non-circles share while extracting permissions
