.drone.yml, lib/Db/CirclesMapper.php, lib/Model/Circle.php, lib/Service/MembersService.php, tests/phpunit.xml, tests/unit/lib/Db/CirclesTest.php, tests/unit/lib/Model/CircleTest.php
Signed-off-by: Maxence Lange maxence@nextcloud.com
=> some more tests

appinfo/routes.php, js/circles.js, js/navigation.js, lib/Api/Circles.php, lib/Api/Sharees.php, lib/AppInfo/Application.php, lib/Controller/BaseController.php, lib/Controller/CirclesController.php, lib/Controller/MembersController.php, lib/Controller/NavigationController.php, lib/Db/CirclesMapper.php, lib/Db/MembersMapper.php, lib/Exceptions/ConfigNoCircleAvailable.php, lib/Model/Circle.php, lib/Service/CirclesService.php, lib/Service/ConfigService.php, lib/Service/MembersService.php, lib/ShareByCircleProvider.php, tests/unit/lib/AppInfo/ApplicationTest.php
Signed-off-by: Maxence Lange maxence@nextcloud.com
=> more tweaks

lib/Db/CirclesMapper.php, lib/ShareByCircleProvider.php
@daita requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/nextcloud/circles/
=> Scrutinizer Auto-Fixes

appinfo/database.xml, appinfo/info.xml, lib/Db/CirclesMapper.php, lib/Db/MembersMapper.php, lib/ShareByCircleProvider.php
Signed-off-by: Maxence Lange maxence@nextcloud.com
=> current_timestamp

tests/phpunit.xml
Signed-off-by: Maxence Lange maxence@nextcloud.com
=> display code coverage in drone ?

js/circles.js
The other stuff won't work when installed within a subfolder :-)
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>
=> Properly generate URLs

js/circles.app.elements.js
Otherwise this leads to some XSS vectors here.
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>
=> Escape HTML elements

appinfo/info.xml, lib/Migration/ImportOwncloudCustomGroups.php
=> Import oc custom groups when possible

lib/Db/CircleProviderRequestBuilder.php
Leftjoin should be significantly faster. Especially if the tables keep
growing.
=> Use LeftJoin to speedup getSharedWith

lib/Activity/Provider.php
Consistent with https://github.com/nextcloud/circles/blob/3723f62ef930d73d59a5a62d637f9c59ef166f76/lib/Activity/Provider.php#L222
=> Spelling: into circle

js/circles.app.navigation.js, js/circles.app.results.members.js, lib/Activity/Provider.php, lib/Db/CirclesRequest.php, lib/Service/FederatedService.php, templates/navigate.php
Signed-off-by: Maxence Lange <maxence@nextcloud.com>
=> first draft

lib/Circles/FileSharingBroadcaster.php
Required due to https://github.com/nextcloud/server/pull/6366
@daita can you release this before 12.0.3 gets out please?
=> Update email usage

js/circles.app.navigation.js
As discussed.
I used a timeout for 500 now, as we have it in the general search field in the top bar in Nc.
=> add delay before search request is sent to server, fixes #123

lib/Service/CirclesService.php, lib/Service/EventsService.php
This is a proposal for solving #129, add hooks so external applications can listen to circle operations.
Tested in tags/v0.12.4
=> Add Circle hooks

lib/Service/EventsService.php
Signed-off-by: Vinicius Cubas Brand <viniciuscb@gmail.com>
=> include needed in EventsService

appinfo/info.xml
Due to changes in https://github.com/nextcloud/server/pull/6328 resp. https://github.com/nextcloud/appstore/pull/521. Let's wait until those PRs are fixed and done. :)
=> adapt info.xml 

appinfo/info.xml
cf https://github.com/nextcloud/appstore/pull/521#issuecomment-332489092 and https://github.com/nextcloud/appstore/pull/521/commits/913742079b97f6c1a003e7b6cfa8a0f17b186110
=> attribute name now follows different case style

appinfo/info.xml, js/admin.js, lib/Api/v1/Circles.php, lib/Api/v1/ShotgunCircles.php, lib/Circles/FileSharingBroadcaster.php, lib/Command/Clean.php, lib/Command/FixUniqueId.php, lib/Controller/NavigationController.php, lib/Db/CircleProviderRequestBuilder.php, lib/Db/CirclesRequest.php, lib/Db/CirclesRequestBuilder.php, lib/Db/CoreRequestBuilder.php, lib/Db/SharingFrameRequest.php, lib/Db/SharingFrameRequestBuilder.php, lib/Service/ConfigService.php, lib/Service/SharingFrameService.php
>     Circles::getSharesFromCircle($circleUniqueId);
will get all the shares from a circle (no limit yet) from the current user session
>     ShotgunCircles::getSharesFromCircle($circleUniqueId, $userId);
will returns all the shares from a circle from this userId point of view (access or not to the circle). userId can be empty.
=> Get shares

lib/ShareByCircleProvider.php
This method allows to find shares to circles, given a fileid
=> Implemented method ShareByCircleProvider->getSharesByPath

lib/Model/Member.php
Is it possible to make "This member is the owner of the circle" be "Owner of circle" ?
While different from the regular structure, I don't see what the extra verbiage adds.
=> Spelling: Marked nouns, in-valid/sufficient

lib/Circles/FileSharingBroadcaster.php
Required against 14 (master) after https://github.com/nextcloud/server/pull/8026 is merged
=> Make sure the share email only ships sane HTML

lib/Activity/Provider.php, lib/Activity/ProviderParser.php, lib/Activity/ProviderSubjectCircle.php, lib/Activity/ProviderSubjectGroup.php, lib/Activity/ProviderSubjectLink.php, lib/Activity/ProviderSubjectMember.php, lib/Api/v1/Circles.php
Fix https://github.com/nextcloud/activity/issues/303
=> Activity fixes

lib/Activity/ProviderParser.php
https://github.com/nextcloud/circles/issues/243
=> Parsing error in activities when user request to join a circle #243

lib/ShareByCircleProvider.php
Should fix issue with mail shares
=> check data structure first

lib/Db/CircleProviderRequestBuilder.php
As already described in #170 the `OCA\Circles\Db\CircleProviderRequest::getFilesForCircles` call creates a huge SQL with really poor performance. This call is critical for overall application performance because it is run nearly all the time. Especially on every `PROPFIND` WebDAV call. And as we all know, there are a massive amount of those calls if you use the WebDAV feature intensive.
Before this PR the resulting SQL executed by this method looks like that:
```sql
SELECT DISTINCT `s`.`id`, 
`s`.*, 
`f`.`fileid`, 
`f`.`path`, 
`f`.`permissions`  AS `f_permissions`, 
`f`.`storage`, 
`f`.`path_hash`, 
`f`.`parent`       AS `f_parent`, 
`f`.`name`, 
`f`.`mimetype`, 
`f`.`mimepart`, 
`f`.`size`, 
`f`.`mtime`, 
`f`.`storage_mtime`, 
`f`.`encrypted`, 
`f`.`unencrypted_size`, 
`f`.`etag`, …
```
=> Use subselects to reduce rows_examined and increase performance

js/admin.js, lib/Controller/NavigationController.php, lib/Controller/SettingsController.php, lib/Model/Member.php, lib/Service/ConfigService.php, lib/Service/MembersService.php, templates/settings.admin.php
=> Add option to allow moderator to add member to closed circle without invitation step

lib/Service/ConfigService.php, lib/Service/MembersService.php
Signed-off-by: Maxence Lange <maxence@artificial-owl.com>
=> settings - limit to accounts

lib/Service/CirclesService.php
Required for https://github.com/nextcloud/deck/pull/1293
=> Return member list when fetching details with force parameter

appinfo/database.xml
=> duplicate primaty on sqlite

lib/Db/SharesRequestBuilder.php, lib/Migration/Version0017Date20200202112903.php, lib/Migration/Version0017Date20200214112607.php
Since Circles [v0.18.2](https://github.com/nextcloud/circles/tree/v0.18.2)
Reference: https://github.com/nextcloud/circles/issues/367#issuecomment-584068412
=> Fix PostgreSQL compatibility

appinfo/info.xml, lib/Circles/FileSharingBroadcaster.php, lib/Command/CirclesCreate.php, lib/Command/CirclesDestroy.php, lib/Command/CirclesDetails.php, lib/Command/CirclesList.php, lib/Command/MembersCreate.php, lib/Command/MembersDetails.php, lib/Command/MembersLevel.php, lib/Command/MembersList.php, lib/Command/MembersRemove.php, lib/Db/CirclesRequest.php, lib/Db/CirclesRequestBuilder.php, lib/Db/CoreRequestBuilder.php, lib/Db/MembersRequest.php, lib/Model/BaseMember.php, lib/Service/CirclesService.php, lib/Service/MembersService.php
Manage circles and members with:
./occ circles:manage:create
./occ circles:manage:list
./occ circles:manage:destroy
./occ circles:manage:details
./occ circles:members:list
./occ circles:members:create
./occ circles:members:details
./occ circles:members:remove
./occ circles:members:level
=> manage circles and members from occ

lib/Controller/SharesController.php, lib/Service/SharingFrameService.php
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>
=> Add more loigging to share creation

templates/navigate.php
Adding the ability to display descriptions in different languages.
=> Descriptions in navigate.php

lib/Activity/ProviderParser.php, lib/Model/BaseMember.php
Fix https://github.com/nextcloud/circles/issues/243
=> Fix Parsing error in activities when user request to join a circle

lib/Service/MembersService.php
=> fix skipped invitation on personal circles

js/circles.app.navigation.js
Get translations for the user level in the personal circle.
=> Get translations for the user level

lib/Api/Circles.php, lib/Api/Sharees.php, lib/Api/v1/Circles.php, lib/Api/v1/ShotgunCircles.php, lib/Cron/ContactsExistingShares.php, lib/Cron/GlobalSync.php, lib/Hooks/UserHooks.php, lib/ShareByCircleProvider.php
=> Fix Application setup

lib/Service/CirclesService.php
=> use UserSession for dav conn

lib/Search/LocalUsers.php
This will also include user type search results for matching email addresses.
=> Include mail matches in the collaborator search

js/circles.app.elements.js
=> fix displayname

js/circles.app.js, js/circles.app.navigation.js, lib/Model/BaseMember.php
Signed-off-by: Sascha Wiswedel <sascha.wiswedel@nextcloud.com>
=> defanged the quite harsh and colloquial "kick member" by "remove"

README.md
Signed-off-by: Sascha Wiswedel <sascha.wiswedel@nextcloud.com>
=> added documentation about membership levels

lib/Service/ConfigService.php
Signed-off-by: Maxence Lange <maxence@artificial-owl.com>
=> print debug link

lib/Migration/Version0019Date20200603080001.php
=> fix setup with nc21

lib/Db/MembersRequest.php, lib/Service/CirclesService.php
=> forceAll in linkedGroups

lib/Command/CirclesTest.php
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
=> l10n: Separate words

appinfo/info.xml
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
=> l10n: Replace apostrophe with double quotation

appinfo/info.xml, composer.lock, lib/Command/CirclesConfig.php, lib/Command/CirclesReport.php, lib/Command/CirclesTest.php, lib/IMemberships.php, lib/Model/Circle.php, lib/Model/FederatedUser.php, lib/Model/ManagedModel.php, lib/Model/Member.php, lib/Model/ModelManager.php, lib/Model/Report.php, lib/Service/FederatedUserService.php
./occ circles:report < report.txt to read it
=> ./occ circles:report to generate obfuscated report

lib/Circles/FileSharingBroadcaster.php, lib/FederatedItems/SingleMemberAdd.php, lib/GlobalScale/FileShare.php, lib/GlobalScale/MemberAdd.php
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
=> l10n: Replace the apostrophe with double quotation

lib/Api/v1/Circles.php, lib/Model/Member.php
=> keeping an illusion of consistency

lib/Command/CirclesMaintenance.php, lib/Cron/Maintenance.php, lib/Db/CoreRequestBuilder.php, lib/Db/EventWrapperRequest.php, lib/Exceptions/MaintenanceException.php, lib/Migration/Version0022Date20220526113601.php, lib/Migration/Version0022Date20220626112233.php, lib/Model/Federated/EventWrapper.php, lib/Service/ConfigService.php, lib/Service/EventWrapperService.php, lib/Service/MaintenanceService.php, lib/Service/MigrationService.php
=> [stable22] maintenance management and federatedEvent retries

lib/FederatedItems/MemberDisplayName.php, lib/Listeners/DeprecatedListener.php
=> Feed FederatedEvent with Initiator as Member

lib/Service/MaintenanceService.php
=> remove echo

.github/workflows/phpunit.yml, lib/Command/CirclesCheck.php
create an empty attachment to avoid timeout
=> avoid timeout during check

lib/Api/v1/Circles.php, lib/CirclesManager.php, lib/CirclesQueryHelper.php, lib/Collaboration/v2/CollaboratorSearchPlugin.php, lib/Command/CirclesList.php, lib/Command/CirclesMemberships.php, lib/Command/CirclesReport.php, lib/Command/SharesFiles.php, lib/Controller/AdminController.php, lib/Controller/RemoteController.php, lib/Db/CircleRequest.php, lib/Db/CoreQueryBuilder.php, lib/Db/MemberRequest.php, lib/Db/ShareWrapperRequest.php, lib/IQueryProbe.php, lib/Listeners/DeprecatedListener.php, lib/Model/Probes/BasicProbe.php, lib/Model/Probes/CircleProbe.php, lib/Model/Probes/MemberProbe.php, lib/Notification/Notifier.php, lib/Service/CircleService.php, lib/Service/ConfigService.php, lib/Service/FederatedUserService.php, lib/Service/MaintenanceService.php, lib/Service/MemberService.php, lib/Service/MembershipService.php, lib/Service/RemoteDownstreamService.php, lib/Service/ShareWrapperService.php, lib/ShareByCircleProvider.php
might be backported to stable22
=> using CircleProbe

lib/Command/MembersList.php, lib/Service/ConfigService.php
=> better display of mail addresses

lib/Service/ConfigService.php, lib/Service/MigrationService.php
child shares are now using singleIds
=> migration to 22.1.0 - child shares

lib/Service/MembershipService.php, lib/Service/MigrationService.php
quickly generate old members' membership during migration
=> generate quick members' memberships during migration

lib/Command/CirclesDetails.php, lib/Controller/AdminController.php, lib/Controller/LocalController.php, lib/Db/CoreQueryBuilder.php, lib/Model/Probes/CircleProbe.php, lib/Service/CircleService.php
Non-Visible Open Circles should returns details to allow visitor requesting membership
=> details on non-visible (but open) circles

lib/Db/MemberRequest.php, lib/FederatedItems/CircleLeave.php, lib/Service/CircleService.php
fix an issue when trying to join a Circle as initiator is empty at the time of the request
=> emulate initiator on CircleJoin

lib/Notification/Notifier.php, lib/Service/MemberService.php
in certain condition `getMemberById()` will only works if we look for direct membership
will require #792
=> fix notification when invited to a circle

appinfo/info.xml, lib/Command/FixInstance.php, lib/Db/MembersRequestBuilder.php
=> fix instances

lib/Service/ConfigService.php
Some small edit to better display usernames, based on their type
=> better display of federated user

lib/Db/CoreQueryBuilder.php, lib/Model/Probes/CircleProbe.php
Will be useful when searching for users as entity
=> allow to visit Single Circle

lib/Service/FederatedUserService.php
force lower case on mail address to avoid duplicate
=> strtolower on mail address

lib/Command/CirclesList.php, lib/Controller/AdminController.php, lib/Controller/LocalController.php, lib/Controller/RemoteController.php, lib/Db/CircleRequest.php, lib/Db/CoreQueryBuilder.php, lib/IQueryProbe.php, lib/Model/Probes/BasicProbe.php, lib/Service/MigrationService.php
=> only returns population on direct request from the front-end or occ command

CHANGELOG.md
I think it would be prudent to warn admins about the issues with the Circles migration.
=> Changelog: add NC22 migration notice, fixes #856

lib/Command/MembersList.php, lib/Service/ConfigService.php
this will make the table displayed when using ./occ circles:members:list _slightly_ smaller
=> remove column instance

lib/ShareByCircleProvider.php
=> exception on null token

lib/Service/SendMailService.php
Reported at Transifex.
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>
=> l10n: Improved grammar

lib/Controller/AdminController.php, lib/Controller/LocalController.php, tests/unit/lib/Controller/AdminControllerTest.php, tests/unit/lib/Controller/LocalControllerTest.php
=> [stable22] Paginate Circles through OCS query parameters

lib/Controller/AdminController.php, lib/Controller/LocalController.php, tests/unit/lib/Controller/AdminControllerTest.php, tests/unit/lib/Controller/LocalControllerTest.php
=> [stable23] Paginate Circles through OCS query parameters

lib/AppInfo/Application.php, lib/Command/CirclesMaintenance.php, lib/Listeners/Files/DestroyingCircle.php, lib/Service/MaintenanceService.php, lib/Service/ShareWrapperService.php
=> [stable23] remove shares during circles destruction, clean orphan shares on cron

lib/AppInfo/Application.php, lib/Command/CirclesMaintenance.php, lib/Listeners/Files/DestroyingCircle.php, lib/Service/MaintenanceService.php, lib/Service/ShareWrapperService.php
=> [stable22] remove shares during circles destruction, clean orphan shares on cron

lib/Service/FederatedUserService.php
=> Fix cached circle returning bool before being parsed as JSON

lib/Tools/Db/ExtendedQueryBuilder.php
https://github.com/nextcloud/server/pull/31609
(no backport !)
=> switching to LoggerInterface

lib/CirclesManager.php, lib/Command/CirclesConfig.php, lib/Exceptions/RemoteCircleException.php, lib/Exceptions/SuperSessionException.php, lib/FederatedItems/CircleConfig.php, lib/FederatedItems/CircleDestroy.php, lib/Model/Circle.php, lib/Model/Member.php, lib/Model/Probes/CircleProbe.php, lib/Service/CircleService.php, lib/Service/ConfigService.php, lib/Service/FederatedUserService.php, lib/StatusCode.php
=> [stable22] limit some feature when Circles is managed by an app

lib/Db/ShareWrapperRequest.php, lib/Listeners/Files/DestroyingCircle.php, lib/Listeners/Files/MembershipsRemoved.php, lib/Service/MaintenanceService.php, lib/Service/ShareWrapperService.php
=> [stable22] remove child shares

lib/Db/ShareWrapperRequest.php, lib/Listeners/Files/DestroyingCircle.php, lib/Listeners/Files/MembershipsRemoved.php, lib/Service/MaintenanceService.php, lib/Service/ShareWrapperService.php
=> [stable23] remove child shares

lib/FederatedItems/CircleEdit.php, lib/Listeners/DeprecatedListener.php, lib/Service/MaintenanceService.php
=> [stable22] update displayName

.github/workflows/phpunit.yml
=> Update stable24 target versions

lib/Db/CoreQueryBuilder.php, lib/Db/ShareWrapperRequest.php
=> +limitToFederatedUserMemberships

lib/Command/CirclesCreate.php
=> [occ] display information about freshly created circle

lib/Db/CoreQueryBuilder.php
=> recursive setOptions()

lib/Service/MigrationService.php
Reverts nextcloud/circles#1080
Merged too early, in RC state.
=> Revert "[stable23] confirm migration feasibility"

lib/Service/MigrationService.php
Reverts nextcloud/circles#1023
Merged too early
=> Revert "confirm migration feasibility"

lib/Tools/Db/ExtendedQueryBuilder.php
=> migration to IQueryFunction

lib/Model/ShareWrapper.php
Fixes https://github.com/nextcloud/circles/issues/1105
=> [stable24] Avoid using non-existing \OCP\Server::get

.github/workflows/static-analysis.yml, composer.json, composer.lock, psalm.xml, tests/psalm-baseline.xml, tests/stub.phpstub
Only merge after the next minor release
=> [stable24] Add psalm

templates/files/list.php
Parts I missed in https://github.com/nextcloud/circles/pull/1115
=> Further cleanup of markup

lib/Service/FederatedEventService.php
=> enforce event on circle creation

lib/Listeners/DeprecatedListener.php
=> ignore no initiator

lib/Listeners/DeprecatedListener.php
=> [stable24] ignore circle with no initiator

templates/files/list.php
Ref https://github.com/nextcloud/server/pull/33379
=> Remove unused markup

composer.json, composer.lock
Auto-generated update of [christophwurst/nextcloud](https://github.com/ChristophWurst/nextcloud_composer/) dependency
=> [stable22] Update christophwurst/nextcloud dependency

lib/Db/ShareWrapperRequest.php, lib/Service/ShareWrapperService.php
=> [stable24] fix limit/offset

lib/Db/ShareWrapperRequest.php, lib/Service/ShareWrapperService.php
=> [stable23] fix limit/offset

.github/workflows/phpunit-mysql.yml, .github/workflows/phpunit-oci.yml, .github/workflows/phpunit-pgsql.yml, .github/workflows/phpunit-sqlite.yml, .github/workflows/static-analysis.yml, .github/workflows/update-christophwurst-nextcloud.yml
=> Adjust testing matrix for Nextcloud 25 on stable25

.github/workflows/update-christophwurst-nextcloud.yml, appinfo/info.xml, composer.json, composer.lock, lib/Circles/FileSharingBroadcaster.php, lib/Collaboration/v2/CollaboratorSearchPlugin.php, lib/Command/MembersSearch.php, lib/Cron/ContactsExistingShares.php, lib/Cron/GlobalSync.php, lib/ISearch.php, lib/Search/Contacts.php, lib/Search/FederatedUsers.php, lib/Search/GlobalScaleUsers.php, lib/Search/LocalGroups.php, lib/Search/LocalUsers.php, lib/Service/SearchService.php, tests/psalm-baseline.xml, tests/stub.phpstub
=> Add Nextcloud 25 support on master

lib/Db/ShareWrapperRequest.php, lib/Service/ShareWrapperService.php
=> [stable22] fix limit/offset

lib/Notification/Notifier.php, lib/Service/FederatedUserService.php
=> [stable22] emulate user on cron

lib/Notification/Notifier.php, lib/Service/FederatedUserService.php
=> [stable23] emulate user on cron

lib/CirclesManager.php, lib/Service/CircleService.php
=> [stable24] cache getCircles() from other app

lib/CirclesManager.php, lib/Service/CircleService.php
=> [stable23] caching getCircles() from other app

lib/Notification/Notifier.php, lib/Service/FederatedUserService.php
=> [stable25] emulate user on cron

.github/workflows/phpunit.yml, lib/Notification/Notifier.php, lib/Service/FederatedUserService.php
=> [stable24] emulate user on cron

lib/CirclesManager.php, lib/Db/CircleRequest.php, lib/Db/CoreQueryBuilder.php, lib/Model/Probes/DataProbe.php, lib/Service/CircleService.php
should fix #1039
This patch add an alternative to `CirclesManager::getCircles()` to retrieve data about Circles based on current session: `CirclesManager::probeCircles()`
- The access right is only based on Cached Memberships, making the `WHERE` condition of the request is a lot lighter,
- The method use `DataProbe` as parameter to add details to each circles returned by the request.
it allows the app using `probeCircles()` to define exactly which data need to be returned.
The way `DataProbe` works is to edit the list of [`Sql Path` available](https://github.com/nextcloud/circles/blob/master/lib/Db/CoreQueryBuilder.php#L84) and only generate request based on this alternate list
>     $circles = $circlesManager->probeCircles();
```
[
{
"id": "k69QCDoZQFucbphq8Ha3JtNIdc4cR3g",
"name": …
```
=> +DataProbe

lib/Api/v1/Circles.php
reactivating getMember from old Circles' API to avoid conflict with current ShareAPIController from core
=> re-activate getMember()

lib/Listeners/Files/RemovingMember.php, lib/Service/ShareWrapperService.php
=> [stable24] remove shares on removing members

lib/Controller/RemoteController.php, lib/FederatedItems/MassiveMemberAdd.php, lib/Service/FederatedEventService.php, lib/Service/GlobalScaleService.php, lib/Service/MemberService.php, lib/Service/RemoteDownstreamService.php, lib/Service/RemoteStreamService.php
Avoid situation where logging an exception generates an exception...
=> avoid exception loop

lib/Command/CirclesCheck.php
Helping adming to set a frontal address.
Code is based on the check on internal address
=> check frontal address

lib/Command/CirclesCheck.php
=> [stable25] check frontal address

lib/Model/ModelManager.php
verify app set in route_to_circle is enabled
=> check app is enabled

lib/FederatedItems/CircleLeave.php, lib/StatusCode.php
=> [stable25] only user can leave circles

lib/Model/ModelManager.php
=> [stable24] check app is enabled

lib/Model/ModelManager.php
=> [stable25] check app is enabled

lib/FederatedItems/CircleLeave.php, lib/StatusCode.php
=> [stable24] only user can leave circles

.gitignore, lib/Command/CirclesTest.php
Reported-by: @CaféTango
Signed-off-by: Jérémie Tarot (@silopolis) <silopolis@gmail.com>
=> String fixes by translators

README.md, lib/AppInfo/Application.php
also, removing deprecated notice in readme
=> cleaning code

lib/Command/CirclesCheck.php, tests/psalm-baseline.xml
backport of https://github.com/nextcloud/circles/pull/1285
=> [stable25] adding clearCacheConfig

lib/Service/ConfigService.php
=> [stable26] fix internal route when using occ

lib/Command/CirclesMaintenance.php, lib/Service/MaintenanceService.php
=> [stable26] refresh display name

lib/Service/ConfigService.php
=> [stable25] fix internal route when using occ

lib/Command/CirclesRemote.php, lib/Controller/RemoteController.php
=> [stable26] allow local ips on globalscale

appinfo/routes.php, css/files/circles.filelist.css, js/files/circles.files.list.js, lib/Api/v1/Circles.php, lib/AppInfo/Application.php, lib/Controller/DeprecatedController.php, tests/psalm-baseline.xml
re-implementation of an old feature: Shared to Circle in the left panel of Files.
The code is slightly updated to today's API, but still marked as deprecated until a cleaner implementation on the front-end.
=> shared to circles

appinfo/routes.php, css/files/circles.filelist.css, js/files/circles.files.list.js, lib/Api/v1/Circles.php, lib/AppInfo/Application.php, lib/Controller/DeprecatedController.php, tests/psalm-baseline.xml
=> [stable26] shared to circles

lib/Db/CoreQueryBuilder.php, lib/Migration/Version0028Date20230705222601.php, lib/Service/SearchService.php, psalm.xml
search should be improved
- prefer probeCircles to getCircles
- do not search on display_name
=> probeCircles on search

lib/Command/CirclesMaintenance.php, lib/Service/MaintenanceService.php
=> [stable25] refresh display name

lib/Service/FederatedUserService.php
- fix an issue when converting group with '@' to federatedUser
- better parsing of federatedId to allow accounts and groups with '@' in globalscale env
=> group can contains '@'

lib/Service/FederatedUserService.php
=> [stable27] group can contains '@'

lib/Db/CoreQueryBuilder.php, lib/Migration/Version0028Date20230705222601.php, lib/Service/SearchService.php, psalm.xml
=> [stable27] probeCircles on search

lib/CirclesQueryHelper.php, lib/Db/CoreQueryBuilder.php
=> [stable27] ignore personal's ownership requirement

lib/CirclesQueryHelper.php, lib/Db/CoreQueryBuilder.php
=> [stable26] ignore personal's ownership requirement

lib/Service/FederatedUserService.php
=> [stable26] group can contains '@'

lib/Service/FederatedUserService.php
=> [stable25] group can contains '@'

lib/CirclesQueryHelper.php, lib/Db/CoreQueryBuilder.php
=> [stable25] ignore personal's ownership requirement

lib/Command/CirclesMaintenance.php, lib/Command/CirclesRemote.php, lib/Controller/RemoteController.php
=> [stable25] allow local ips on globalscale

lib/Model/ModelManager.php
condition was wrongly set: we want the app set as route to be enabled.
=> generate path if app _DOES_ exist

composer.json, composer.lock
Auto-generated update of [nextcloud/ocp](https://github.com/nextcloud-deps/ocp/) dependency
=> [stable25] Update nextcloud/ocp dependency

.github/workflows/phpunit-mysql.yml, .github/workflows/phpunit-oci.yml, .github/workflows/phpunit-pgsql.yml, .github/workflows/phpunit-sqlite.yml, composer.json, composer.lock, lib/AppInfo/Capabilities.php, tests/psalm-baseline.xml
Auto-generated update of [nextcloud/ocp](https://github.com/nextcloud-deps/ocp/) dependency
=> [stable26] Update nextcloud/ocp dependency

.github/workflows/phpunit-mysql.yml, .github/workflows/phpunit-oci.yml, lib/Model/ModelManager.php
=> [stable27] generate path if app does exist

lib/Model/ModelManager.php
=> [stable26] generate path if app does exist

lib/Model/ModelManager.php
=> [stable25] generate path if app does exist

lib/ShareByCircleProvider.php
backport of #1223
switching back `probeCircle()` to deprecated `getCircle()`
=> [stable25] restore deleted share

lib/AppInfo/Application.php, lib/Db/CoreQueryBuilder.php, lib/FederatedItems/MemberDisplayName.php, lib/Listeners/Files/ListenerFilesLoadScripts.php, psalm.xml
- use of LoadAdditionnalScriptsEvent from Files,
- clean Application.php,
- fix an issue with display name update on almost-member in globalscale env.
=> get rid of generic events

lib/Controller/DeprecatedController.php
=> [stable26] filter system circles

lib/Model/FileCacheWrapper.php, lib/ShareByCircleProvider.php
=> [stable26] support files_external

lib/Db/CoreRequestBuilder.php, lib/Db/ShareWrapperRequest.php, lib/Model/ShareWrapper.php, lib/Service/CircleService.php, lib/ShareByCircleProvider.php, psalm.xml, tests/psalm-baseline.xml
=> [stable26] download permissions on share for internal/external members

lib/Db/CoreRequestBuilder.php, lib/Db/ShareWrapperRequest.php, lib/Model/ShareWrapper.php, lib/Service/CircleService.php, lib/ShareByCircleProvider.php, psalm.xml, tests/psalm-baseline.xml
=> [stable27] download permissions on share for internal/external members

lib/Controller/DeprecatedController.php
=> [stable27] filter system circles

js/files/circles.files.list.js
=> [stable27] escape html

js/files/circles.files.list.js
=> [stable26] escape html

lib/Db/CircleRequest.php
display circles with same-level of membership in alphabetic order
=> order by level and displayname

lib/Db/CircleRequest.php
=> [stable27] order by viewer level

lib/Model/Circle.php
Fix https://github.com/nextcloud/circles/issues/829
_Superseed https://github.com/nextcloud/circles/pull/992 (DCO and squash errors...)_ 🚯
=> fix incorrect Date format detection

lib/Db/CircleRequest.php
=> [stable26] order by viewer level

lib/Command/CirclesSync.php, lib/Db/AccountsRequest.php, lib/Search/LocalUsers.php, lib/Service/FederatedUserService.php, lib/Service/MaintenanceService.php, lib/Service/SyncService.php
=> [stable27] lighter name update

.github/workflows/phpunit-mysql.yml, .github/workflows/update-nextcloud-ocp.yml, appinfo/info.xml
=> feat(deps): Add Nextcloud 29 support on master

lib/Db/ShareWrapperRequest.php, lib/Model/ShareWrapper.php, lib/ShareByCircleProvider.php
store expiration on share update
=> store expiration date

lib/Db/ShareWrapperRequest.php, lib/Model/ShareWrapper.php, lib/ShareByCircleProvider.php
=> [stable25] share expiration date

.github/workflows/phpunit-mysql.yml, .github/workflows/phpunit-oci.yml, .github/workflows/phpunit-pgsql.yml, .github/workflows/phpunit-sqlite.yml, composer.json, composer.lock
=> chore(CI): Adjust testing matrix for Nextcloud 29 on stable29

lib/Activity/ProviderParser.php, lib/Activity/ProviderSubjectCircleMember.php, lib/Service/ActivityService.php
fixing missing link and displayed message
=> fixing group activities

lib/Activity/ProviderParser.php
=> [stable29] set remote as email

lib/Activity/ProviderParser.php, lib/Activity/ProviderSubjectCircleMember.php, lib/Service/ActivityService.php
=> [stable29] fixing group activities

lib/Service/SearchService.php
=> [stable26] switch to getCircles()

lib/Activity/ProviderParser.php
=> [stable27] set remote as email

lib/Db/CoreQueryBuilder.php, lib/Db/ShareWrapperRequest.php
=> [stable27] fix search on circles share

lib/Service/SearchService.php
=> [stable27] switch to getCircles()

lib/Activity/ProviderParser.php
=> [stable26] set remote as email

lib/Activity/ProviderParser.php
=> [stable28] set remote as email

lib/FederatedItems/SingleMemberAdd.php
=> [stable26] remove debug logs

lib/Db/CoreQueryBuilder.php, lib/Db/ShareWrapperRequest.php
=> [stable26] fix search on circles share

lib/Service/SearchService.php
=> [stable28] switch to getCircles()

lib/Db/CoreQueryBuilder.php, lib/Db/ShareWrapperRequest.php
=> [stable28] fix search on circles share

lib/Command/CirclesMaintenance.php, lib/Service/MaintenanceService.php
- fix users display name update by using `IUser` API instead of Accounts
- add occ command to update single display name
- add occ command to update full list of users from the table user_saml_users
=> fix saml users displayname

lib/Command/CirclesMaintenance.php, lib/Service/MaintenanceService.php
=> [stable29] fix saml users displayname

lib/Command/CirclesMaintenance.php, lib/Service/MaintenanceService.php, lib/ShareByCircleProvider.php
=> [stable28] fix saml users displayname

lib/Command/CirclesMaintenance.php, lib/Service/MaintenanceService.php, lib/ShareByCircleProvider.php
=> [stable27] fix saml users displayname

lib/Activity/ProviderSubjectCircleMember.php
=> chore(i18n): Established the meaning of the sentence

lib/Activity/Provider.php
=> [stable27] fix setIcon using svg

lib/Dashboard/TeamDashboardWidget.php
- Ref https://github.com/nextcloud/server/pull/46448
Before | After
---|---
=> fix(dashboard): Fix dashboard icon

lib/Service/NotificationService.php
* Resolves https://github.com/nextcloud/circles/issues/1651
The URL needs to be absolute to work also on mobile and desktop clients.
=> fix(notification): Make sure the action URL is an absolute URL

lib/Db/EventWrapperRequest.php, lib/Service/MaintenanceService.php
keep table clean: delete 1 month old federated event that are noted as terminated
=> new daily maintenance to delete old federated events

lib/ShareByCircleProvider.php
=> Share must be linked to an existing circle

lib/AppInfo/Application.php
On the server side we never read this registration, so it is useless.
=> chore(Application): Remove unused files navigation registration

lib/Db/ShareWrapperRequest.php
fix the management of download permission, bugged since 29.0.9.
v30+ not affected
=> fix download permission

lib/Command/MigrateCustomGroups.php
=> ignore non-existant users

lib/Service/FederatedUserService.php
keep original display name on local user if known
=> do not refresh display name on known local user

composer.json
Fixes https://github.com/nextcloud/circles/actions/runs/15823008864/job/44596370781?pr=2042
=> build(composer): Stop main composer.json updates propagating to vendor-bin

composer.lock, tests/psalm-baseline.xml
Fixes https://github.com/nextcloud/circles/issues/2060
=> [stable30] chore(dev-deps): Bump nextcloud/ocp package

.github/workflows/update-nextcloud-ocp.yml, appinfo/info.xml, package-lock.json, package.json
=> feat(deps): Add Nextcloud 33 support on master

composer.lock, lib/ShareByCircleProvider.php
Auto-generated update of [nextcloud/ocp](https://github.com/nextcloud-deps/ocp/) dependency
=> [master] Update nextcloud/ocp dependency

composer.lock, lib/Model/ShareWrapper.php
Auto-generated update of [nextcloud/ocp](https://github.com/nextcloud-deps/ocp/) dependency
=> [stable30] Update nextcloud/ocp dependency
